### ISSUE TITLE
Sharing my Sass work

### ISSUE THREAD

**Issue by instance-id** [LonelyVertex/unity-sass-importer#1]
Hey there,
    I came across this just now and thought you might be interested in having a look at the sass importer I made a little while back. I implemented @use functionality for partial files, and use a powershell script setup as an 'external tool' in Rider so I can just right click on my folder, enter a name and it automatically creates my main sass template, and a number of partial files for containers, fields, etc. Hot-reload and everything works great, though there was a slight issue in 2022.2 beta that caused a weird broken import of the actual USS file, but I just updated it with a fix. (I have not tested anything in Windows, though, as I use Linux.)

https://gist.github.com/instance-id/e5bf308f3d7779fcfdaa1dd8e137d621

Example: If I create a Style folder and pass that to the pwsh script, this is the end result (minus the USS, which is created/updated during the import into Unity)

```powershell
./create_sass_template.ps1 -basePath /path/to/whatever/Style -fileName SectionElementStyle
```

![](https://img.instance.id/y29oqUqhUw6p/direct)

**Comment by Mirovsky** [comment]
Nice! I stumbled upon few importers for `.sass` files, but each (and yours) had same issue for me - they all created `.uss` file along the `.sass` files. I don't like to keep track of what files should be moved together etc... (enough with Unity's `.meta` files). But I wasn't aware of `@use` and I implemented only `@import`. I managed to resolve all dependencies while importing stylesheets and then run uss stylesheet importer, which results in single file usable as stylesheet on its own. All imports are resolved by Unity, the only thing I had to do is parsing the imports (which I will extend to `@use`), but it's only for triggering the import of the main asset if some of its dependencies change.
